In [1]:
import numpy as np
import random

In [2]:
class Product:
    # constructor
    def __init__(self, id_, price_list):
        self.id_ = id_
        # possible choices of price
        self.price_list = price_list
        # actual price
        self.price = price_list[0]
        # index of the actual price
        self.idx = 0
        # self.secondaries = [] secondaries slots of a prouct are chosen by the graph of influence probabilities, generated for each user

    # set the four new possible choices of the prices
    def set_new_price_list(self, price_list):
        self.price_list = price_list
        self.price = price_list[0]


    # change the actual price between one of the possible choice ordered with increasing prices
    def change_price(self, new_index):
        self.price = self.price_list[new_index]


    # increase by one step the price in the vector of possible prices
    def increase_price(self):
        if self.price == max(self.price_list):
            return
        else:
            self.price = self.price_list[self.idx + 1]
            self.idx += 1


    # decrease by one step the price in the vector of possible prices
    def decrease_price(self):
        if self.price == min(self.price_list):
            return
        else:
            self.price = self.price_list[self.idx - 1]
            self.idx -= 1

In [18]:
P1 = Product(0,[10,13,16,19])
P2 = Product(1,[20,23,26,29])
P3 = Product(2,[30,33,36,39])
P4 = Product(3,[40,43,46,49])
P5 = Product(4,[50,53,56,59])

products = [P1,P2,P3,P4,P5]

In [39]:
# superclass
class User:
    # constructor
    def __init__(self, primary):
        # for each product an user has a reservation price
        self.reservation_price = [] # 5x1
        # stores the id {0,1,2,3,4} of products clicked
        self.products_clicked = []
        # stores the id {0,1,2,3,4} of products bought
        self.cart = []
        # stores the quantities of items bought for each product
        self.quantities = []
        # graph with the influence probabilities between the products
        self.P = np.zeros((5,5))
        # primary product shown
        self.primary = primary # {0,1,2,3,4} 


    # graph with the click probabilities on the products 
    def generate_graph(self, distribution):
        graph = np.zeros((5,5))
        graph = distribution
        return graph
            


# Inheritance
# 3 classes of users:

# targeted buyer, lower probability to click other products after the first
class User0(User):
    def __init__(self, primary):
        User.__init__(self, primary)
        self.reservation_price = [15,25,35,45,55] + np.random.normal(1, scale=3, size=5) # average reservation price
        self.P = User.generate_graph(self, np.random.uniform(0, 0.5, size=(5,5))) #lower influence probabilities


# curious buyer, more variable budget, higher probability to click on other products
class User1(User):
    def __init__(self, primary):
        User.__init__(self, primary)
        self.reservation_price = [15,25,35,45,55] + np.random.normal(1, scale=5, size=5) # more variable reservation price
        self.P = User.generate_graph(self, np.random.uniform(0.2, 1, size=(5,5))) # higher influence probabilities


# buyer with higher budget 
class User2(User):
    def __init__(self, primary):
        User.__init__(self, primary)
        self.reservation_price = 10 + [15,25,35,45,55] + np.random.normal(1, scale=3, size=5) # higher reservation price
        self.P = User.generate_graph(self, np.random.uniform(0, 1, size=(5,5))) # more variable influence probabilities
        


In [20]:
# Each day we have a list of users who enter the website, distributed with respect to their classes
class Daily_Customers:
   # constructor
    def __init__(self):
        self.Users = []

    
    # which type of user has to be created (which class)
    def whichUser(self, binary_vector, primary):
      if np.sum(binary_vector==0):
          self.Users.append(User0(primary))
      elif np.sum(binary_vector==1):
          self.Users.append(User1(primary))    
      elif np.sum(binary_vector==2):
          self.Users.append(User2(primary))


    # generate new users for the day
    def UsersGenerator(self, num_users, binary_vector):
        #create "alpha_ratio * num_users" users, without the alpha_0 in competitor website
        users_per_product = np.random.multinomial(num_users, np.random.dirichlet(np.ones(5)))
        for i in range(len(users_per_product)):
            print(users_per_product[i], "users with primary product", i+1)
            for j in range(users_per_product[i]):
                self.whichUser(binary_vector, i) #i is the index of the primary product
                

In [22]:
# Example
Day_0 = Daily_Customers()
Day_0.UsersGenerator(1000, np.array([0,1]))

25 users with primary product 1
456 users with primary product 2
25 users with primary product 3
394 users with primary product 4
100 users with primary product 5


In [50]:
class E_commerce:
    # constructor
    def __init__(self):
        # list of products
        self.products = []
        # list of lists of users
        self.daily_users = []
        # dataset with the history of products visited by each user in each day
        self.time_history = []
        # amount of money spent by the users, to implement in future
        self.cash = 0 
        # probability that the user checks the second product
        self.lambda_ = 0.5
        #number of clicks per product
        self.graph = self.generate_graph(np.ones(5))


    def set_lambda(self, new_lambda):
        self.lambda_ = new_lambda
    
    
    def add_product(self, product):
        self.products.append(product)
    
    
    def set_products(self, product_list):
        self.products = product_list

    # graph with the probabilities to see the products 
    # 1 for the first secondary slot, lambda for the second one
    def generate_graph(self, distribution):
        graph = np.zeros((5,5))
        for i in range(5):
          # secondary slots indexes (0,1,2,3,4,5)-{i=primary}
          j = np.random.choice([x for x in range(5) if x != i ],2, replace = False) 
          # probability to see the first slot = 1
          graph[i,j[0]] = distribution[i]
          # 1 * lambda 
          graph[i,j[1]] = distribution[i] * self.lambda_
        return graph
    

    # simulate a day of visits in the website
    def simulate_day(self, num_users, binary_vector):
        D = Daily_Customers()
        D.UsersGenerator(num_users, binary_vector)
        self.daily_users.append(D.Users)
        # store the visits of the day
        Day = []
        # for each user visit (each day we can change the prices: we have to implement it)
        for i in range(num_users):
            visit = self.visit(D.Users[i])
            Day.append(visit)
        self.time_history.append(Day)
        return Day
      


    # simulate when an user visits the website
    def visit(self, user):
        # Influence probability matrix of the products, for each user equal to the see probability*click probability
        prob_matrix = user.P * self.graph
        n_nodes = prob_matrix.shape[0]

        # if user's reservation price is lower than the price of the primary product -> end the visit
        if user.reservation_price[user.primary] < self.products[user.primary].price:
            user.products_clicked = [user.primary]
            history_purchase = []
            user.cart = []
            user.quantities = np.zeros(user.P.shape[0])
            active_nodes = np.zeros(n_nodes)
            active_nodes[user.primary] = 1
            return np.array([active_nodes])

        # Influence probability matrix of the products, for each user equal to the see probability*click probability
        prob_matrix = user.P * self.graph
        n_nodes = prob_matrix.shape[0]
        active_nodes = np.zeros(n_nodes)
        active_nodes[user.primary] = 1
        newly_active_nodes = active_nodes
        round = 0

        # store index of products clicked
        history_click = [user.primary] 
        # store products bought
        history_purchase = [user.primary] 
        # store products shown to the user but maybe not clicked or bought
        history_nodes = np.array([active_nodes]) 
        
        # store the prices of the 5 products in an array
        prod_prices = np.zeros(len(self.products))
        for i in range(len(self.products)):
            prod_prices[i] = self.products[i].price

        #user can't click again on products already bought
        prob_matrix[:, user.primary] = 0.

        while(round < 5 and np.sum(newly_active_nodes)>0):

            p = (prob_matrix.T * active_nodes).T
            products_clicked = p > np.random.rand(p.shape[0], p.shape[1])

            prob_matrix = prob_matrix * ((p!=0)==products_clicked)
            newly_active_nodes = (np.sum(products_clicked, axis=0)>0) * (1-active_nodes)

            #user can't click again on product already clicked
            prob_matrix[:, newly_active_nodes==1] = 0.
            
            # slots clicked
            secondary_slots = np.where(newly_active_nodes == 1)[0] 

            # check idxs which match the reservation price
            stop_idxs = np.where(np.array(user.reservation_price)[secondary_slots] < prod_prices[secondary_slots])
            go_idxs = np.where(np.array(user.reservation_price)[secondary_slots] >= prod_prices[secondary_slots])

            #users don't buy products higher than their reservation price
            #so the visit can't go on for theese idxs because no secondary products are shown, since the primary isn't bought
            prob_matrix[secondary_slots[stop_idxs],:] = 0.

            active_nodes = newly_active_nodes
            round += 1

            history_click.append(np.where(newly_active_nodes==1)[0])
            history_purchase.append(secondary_slots[go_idxs])
            history_nodes = np.concatenate((history_nodes, [newly_active_nodes]),axis=0)

        # for better visualization of the array
        history_click =  history_click[:-1] 
        user.products_clicked = history_click
        history_purchase = history_purchase[:-1]
        user.cart = history_purchase

        # estimate random quantities for each product
        if(len(history_purchase)!=0):
            for i in range(len(history_purchase)):
                if(np.size(history_purchase[i])!=0):
                    for j in range(np.size(history_purchase[i])):
                        user.quantities.append(1 + np.random.randint(3, size = 1)[0]) # from 1 to 3 units bought
        #print(history_nodes)
        return history_nodes
    

In [43]:
#TEST VISIT FUNCTION

# users of the day
Day_test = Daily_Customers()
Day_test.UsersGenerator(1, np.array([0,0])) # 1 user of 1st class

#products
P1 = Product(0,[10,13,16,19])
P2 = Product(1,[20,23,26,29])
P3 = Product(2,[30,33,36,39])
P4 = Product(3,[40,43,46,49])
P5 = Product(4,[50,53,56,59])
products = [P1,P2,P3,P4,P5]

#E_commerce inizialization
E = E_commerce()
E.set_products(products)
E.set_lambda(0.5)

U = Day_test.Users[0]
print(U.P * E.graph)
print("############################################################")
visit = E.visit(U)
print(visit)

0 users with primary product 1
0 users with primary product 2
0 users with primary product 3
0 users with primary product 4
1 users with primary product 5
[[0.         0.         0.         0.0161911  0.07561759]
 [0.12344436 0.         0.18152899 0.         0.        ]
 [0.         0.         0.         0.08374601 0.40206718]
 [0.         0.15463168 0.06880117 0.         0.        ]
 [0.         0.20153521 0.         0.43733288 0.        ]]
############################################################
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
clicks = U.products_clicked
cart = U.cart
print(clicks)
print("***************************")
print(cart)
print("***************************")
print(U.quantities)

[4, array([1, 3]), array([0, 2])]
***************************
[4, array([1, 3]), array([0, 2])]
***************************
[3, 1, 3, 2, 2]


In [45]:
num_different_items_bought = len(U.quantities)
num_total_quantities = np.sum(U.quantities)

num_different_items_bought, num_total_quantities

(5, 11)

In [46]:
def estimate_probabilities(dataset, node_index, n_nodes):
    estimated_prob = np.ones(n_nodes)*1.0/(n_nodes-1)
    credits = np.zeros(n_nodes)
    occur_v_active = np.zeros(n_nodes)
    #n_episodes = len(dataset)
    for episode in dataset:
        idx_w_active = np.argwhere(episode[:, node_index] ==1).reshape(-1)
        if len(idx_w_active)>0 and np.any(idx_w_active>0):
            active_nodes_in_prev_step = episode[idx_w_active - 1, :].reshape(-1)
            credits += active_nodes_in_prev_step/np.sum(active_nodes_in_prev_step)
        for v in range(0,n_nodes):
            if(v!=node_index):
                idx_v_active = np.argwhere(episode[:, v] == 1).reshape(-1)
                if (len(idx_v_active)>0 and len(idx_w_active)==0) or (np.any(idx_v_active<idx_w_active) and len(idx_v_active)>0):
                    occur_v_active[v]+=1
    estimated_prob = np.nan_to_num(credits/occur_v_active)
    return estimated_prob

In [58]:
#TEST ESTIMATE PROBABILITIES

P1 = Product(0,[10,13,16,19])
P2 = Product(1,[20,23,26,29])
P3 = Product(2,[30,33,36,39])
P4 = Product(3,[40,43,46,49])
P5 = Product(4,[50,53,56,59])
products = [P1,P2,P3,P4,P5]

#E_commerce inizialization
E = E_commerce()
E.set_products(products)
E.set_lambda(0.5)

num_users = 10000
binary_vector = np.array([0,1])


num_products = 5
n_nodes = num_products
node_index = 0
dataset = []

dataset = E.simulate_day(num_users, binary_vector)
for node_index in [0,1,2,3,4]:
  estimated_prob = estimate_probabilities(dataset=dataset, node_index=node_index, n_nodes=n_nodes) #estimate influence probabilities
  print("Estimated P Matrix: ", estimated_prob) # probability starting from node_index to reach other nodes


1028 users with primary product 1
1624 users with primary product 2
6025 users with primary product 3
302 users with primary product 4
1021 users with primary product 5


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


Estimated P Matrix:  [0.         0.11367347 0.         0.13033954 0.1234375 ]
Estimated P Matrix:  [0.00431965 0.         0.11175899 0.21847826 0.00078493]
Estimated P Matrix:  [0.12293388 0.0005698  0.         0.00407609 0.00208457]
Estimated P Matrix:  [0.00614092 0.00799481 0.00137185 0.         0.23773758]
Estimated P Matrix:  [0.25694996 0.23302961 0.23381706 0.         0.        ]
